name: Java CI with Maven

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/maven:3.9.9-eclipse-temurin-24
    steps:
      - name: Clone repository
        run: git clone --depth 1 https://git.aze.sh/aze/GLaDOS .

      - name: Build with Maven
        run: mvn package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GLaDOS
          path: target/GLaDOS-2.0.0.jar
