name: Java CI with Maven

on:
  push:

jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/maven:3.9.9-amazoncorretto-21-debian-bookworm
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GLaDOS
          path: target/GLaDOS-*.jar
