name: Build and publish GLaDOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/docker:27.3.1-cli
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Check Docker environment
        run: |
          echo "== Environment variable DOCKER_HOST =="
          echo "${DOCKER_HOST:-<not set>}"

          echo
          echo "== Check if /var/run/docker.sock exists =="
          ls -l /var/run/docker.sock || echo "❌ Socket not found"

          echo
          echo "== Check Docker daemon connectivity =="
          docker version || echo "❌ Docker daemon not reachable"

      - name: Clone repository
        run: git clone --depth 1 https://git.aze.sh/aze/GLaDOS .

      - name: Build docker image
        run: docker build -t glados:latest .

