name: Build and publish GLaDOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: docker
    services:
      docker:
        image: docker:27.3.1-dind
        privileged: true
        ports:
          - 2375:2375
        options: --privileged
    container:
      image: docker:27.3.1-cli
      env:
        DOCKER_HOST: tcp://docker:2375
    steps:
      - name: Clone repository
        run: git clone --depth 1 https://git.aze.sh/aze/GLaDOS .

      - name: Build docker image
        run: docker build -t glados:latest .

