name: Build and publish GLaDOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/docker:27.3.1-cli
    steps:
      - name: Clone repository
        run: git clone --depth 1 https://git.aze.sh/aze/GLaDOS .

      - name: Build docker image
        image: docker:latest
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        commands:
          - docker build -t glados:latest .
          - docker images

      # - name: Install node for upload Artifact
      #   run: apt update && apt install nodejs -y

      # - name: Upload final jar artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: GLaDOS
      #     path: target/GLaDOS-2.0.0.jar

      # - name: Upload items artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: items
      #     path: items/*
