name: Build

on:
- push

jobs:
  build:
    name: Build
    runs-on: docker

    steps:
    - uses: actions/checkout@v4
      name: Checkout repo

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn install

    - uses: actions/upload-artifact@v4
      name: Upload Artifact
      with:
        name: GLaDOS
        path: target/GLaDOS-*.jar
