name: Java CI with Maven

on:
  push:

jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/maven:3.9.9-eclipse-temurin-21
    steps:
      - name: Clone repository
        run: |
          git clone --depth 1 https://git.aze.sh/aze/GLaDOS .

      - name: Build with Maven
        run: mvn install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GLaDOS
          path: target/GLaDOS-*.jar
