name: Build and publish GLaDOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/docker:27.3.1-dind
    steps:
      - name: Clone repository
        run: git clone --depth 1 https://git.aze.sh/aze/GLaDOS .

      - name: Build docker image
        run: docker build -t glados:latest .

