name: Java CI with Maven

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/maven:3.9.9-eclipse-temurin-24
      options: --entrypoint /bin/bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile with Maven
        run: mvn clean package

      - name: Upload GLADOS.jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: GLADOS
          path: target/GLADOS.jar
