name: Build

on:
- push
- pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout repo

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn install

    - uses: actions/upload-artifact@v4
      name: Upload Artifact
      with:
        name: GLaDOS
        path: target/GLaDOS-*.jar
